import { mkdir, readFile, readdir, stat, writeFile } from 'node:fs/promises'
import { dirname, extname, join, relative, resolve, sep } from 'node:path'

const GENERATED_HEADER = '// This file is generated by @starter-solutions/inertia-module-utils. Do not edit.\n\n'

export async function generateModuleFiles(config, options = {}) {
  validateConfig(config)

  const cwd = resolve(options.cwd ?? process.cwd())
  const pagesFile = resolve(cwd, config.pagesFile)
  const backendTypesFile = resolve(cwd, config.backendTypesFile)
  const outputs = new Map([
    [pagesFile, await generatePages(config, cwd)],
    [backendTypesFile, await generateBackendTypes(config, cwd)],
  ])
  const changed = []

  for (const [file, content] of outputs) {
    const current = await readOptionalFile(file)

    if (current === content) continue

    changed.push(relative(cwd, file))

    if (!options.check) {
      await mkdir(dirname(file), { recursive: true })
      await writeFile(file, content)
    }
  }

  return {
    files: [...outputs.keys()].map((file) => relative(cwd, file)),
    changed,
    checkFailed: Boolean(options.check && changed.length),
  }
}

export async function generatePages(config, cwd = process.cwd()) {
  const pagesRoot = resolve(cwd, config.pagesDir)
  const outputRoot = dirname(resolve(cwd, config.pagesFile))
  const vueFiles = (await walkFiles(pagesRoot)).filter((file) => extname(file) === '.vue')
  const files = []

  for (const file of vueFiles) {
    if ((await readFile(file, 'utf8')).trim()) files.push(file)
  }
  const entries = files.map((file) => {
    const page = relative(pagesRoot, file).slice(0, -4).split(sep).join('/')
    let importPath = relative(outputRoot, file).split(sep).join('/')
    if (!importPath.startsWith('.')) importPath = `./${importPath}`
    return `  '${config.namespace}/${page}': () => import('${importPath}'),`
  })

  return `${GENERATED_HEADER}export const pages = {\n${entries.join('\n')}\n} as const\n\nexport type ModulePageName = keyof typeof pages\n`
}

export async function generateBackendTypes(config, cwd = process.cwd()) {
  const phpRoot = resolve(cwd, config.phpDir)
  const sourceRoots = config.phpSources.map((source) => resolve(phpRoot, source))
  const files = (await Promise.all(sourceRoots.map(walkFiles))).flat().filter((file) => extname(file) === '.php')
  const sources = await Promise.all(files.map(async (file) => readFile(file, 'utf8')))
  const enumNames = new Set(sources.flatMap(findEnumNames))
  const enumSuffix = config.enumSuffix ?? 'Enum'
  const declarations = []

  for (const source of sources) {
    declarations.push(
      ...parseEnums(source, enumSuffix),
      ...parseDataObjects(source, enumNames, enumSuffix),
    )
  }

  declarations.sort((left, right) => left.name.localeCompare(right.name))

  return `${GENERATED_HEADER}${declarations.map((item) => item.code).join('\n\n')}${declarations.length ? '\n' : ''}`
}

function findEnumNames(source) {
  return [...source.matchAll(/enum\s+(\w+)\s*:\s*(?:string|int)\s*\{/g)]
    .map((match) => match[1])
}

function parseEnums(source, enumSuffix) {
  const declarations = []
  const pattern = /enum\s+(\w+)\s*:\s*(string|int)\s*\{([\s\S]*?)\n\}/g

  for (const match of source.matchAll(pattern)) {
    const [, name, backingType, body] = match
    const cases = [...body.matchAll(/case\s+(\w+)\s*=\s*(['"])(.*?)\2\s*;/g)]
    if (!cases.length) continue
    const values = cases.map((entry) => {
      const value = backingType === 'int' ? entry[3] : JSON.stringify(entry[3])
      return `  ${entry[1]}: ${value},`
    })
    const generatedName = `${name}${enumSuffix}`
    declarations.push({
      name: generatedName,
      code: `export const ${generatedName} = {\n${values.join('\n')}\n} as const\n\nexport type ${generatedName} = typeof ${generatedName}[keyof typeof ${generatedName}]`,
    })
  }

  return declarations
}

function parseDataObjects(source, enumNames, enumSuffix) {
  const classMatch = source.match(/(?:readonly\s+)?class\s+(\w+)[^{]*\{([\s\S]*)\}\s*$/)
  if (!classMatch) return []

  const constructor = classMatch[2].match(/function\s+__construct\s*\(([\s\S]*?)\)\s*\{/)
  if (!constructor) return []

  const properties = [...constructor[1].matchAll(/public\s+(?:readonly\s+)?([?\\\w|]+)\s+\$(\w+)/g)]
  if (!properties.length) return []

  const aliases = parsePhpUseAliases(source)
  const fields = properties.map((property) =>
    `  ${property[2]}: ${phpTypeToTypeScript(property[1], enumNames, enumSuffix, aliases)}`,
  )
  return [{ name: classMatch[1], code: `export interface ${classMatch[1]} {\n${fields.join('\n')}\n}` }]
}

function parsePhpUseAliases(source) {
  const aliases = new Map()

  for (const match of source.matchAll(/^use\s+(?!function\s|const\s)([^;]+);/gm)) {
    const importMatch = match[1].trim().match(/^([\\\w]+?)(?:\s+as\s+(\w+))?$/i)
    if (!importMatch) continue

    const importedName = importMatch[1].split('\\').at(-1)
    aliases.set(importMatch[2] ?? importedName, importedName)
  }

  return aliases
}

function phpTypeToTypeScript(type, enumNames, enumSuffix, aliases) {
  const nullable = type.startsWith('?')
  const normalized = type.replace(/^\?/, '').split('|').map((part) => {
    const short = part.split('\\').at(-1)
    const resolved = aliases.get(short) ?? short
    if (enumNames.has(resolved)) return `${resolved}${enumSuffix}`
    return ({ int: 'number', float: 'number', string: 'string', bool: 'boolean', array: 'unknown[]', mixed: 'unknown' })[short] ?? short
  }).join(' | ')
  return nullable ? `${normalized} | null` : normalized
}

async function walkFiles(root) {
  try {
    if (!(await stat(root)).isDirectory()) return []
  } catch (error) {
    if (error?.code === 'ENOENT') return []
    throw error
  }

  const entries = await readdir(root, { withFileTypes: true })
  const files = await Promise.all(entries.map((entry) => {
    const path = join(root, entry.name)
    return entry.isDirectory() ? walkFiles(path) : [path]
  }))
  return files.flat().sort()
}

async function readOptionalFile(file) {
  try {
    return await readFile(file, 'utf8')
  } catch (error) {
    if (error?.code === 'ENOENT') return null
    throw error
  }
}

function validateConfig(config) {
  for (const key of ['namespace', 'pagesDir', 'pagesFile', 'phpDir', 'backendTypesFile']) {
    if (!config || typeof config[key] !== 'string' || !config[key]) {
      throw new Error(`inertia-module config requires a non-empty ${key}`)
    }
  }
  if (!Array.isArray(config.phpSources)) throw new Error('inertia-module config requires phpSources')
}
