// This file is generated by @starter-solutions/inertia-module-utils. Do not edit.

export const pages = {
  'AaaModuleTemplateZzz/Index': () => import('./pages/Index.vue'),
  'AaaModuleTemplateZzz/Tests/Edit': () => import('./pages/Tests/Edit.vue'),
  'AaaModuleTemplateZzz/Tests/Index': () => import('./pages/Tests/Index.vue'),
} as const

export type ModulePageName = keyof typeof pages
